/* 菌譜 — 抗菌薬の系統分類（早見表）
 *
 * 「イミペネムって何系だっけ」を1秒で引くための表。
 * 系統がわかれば、自然耐性の意味もスペクトラムも芋づるで思い出せる。
 *
 * これも下書き。自施設の採用薬・略号と突き合わせて直す。
 */

const DRUG_CLASSES = [
  {
    id: 'penicillin',
    name: 'ペニシリン系',
    en: 'Penicillins',
    big: 'βラクタム系',
    spectrum: 'グラム陽性球菌（溶連菌・肺炎球菌）／腸球菌(ABPC)／リステリア(ABPC)／一部のグラム陰性桿菌',
    note: '細胞壁合成（PBP）を阻害する。βラクタマーゼで壊される。',
    items: [
      { abbr: 'PCG', jp: 'ベンジルペニシリン（ペニシリンG）', memo: '溶連菌・肺炎球菌・梅毒。グラム陽性菌の基本。' },
      { abbr: 'ABPC', jp: 'アンピシリン', memo: 'PCGにグラム陰性活性を足したもの。腸球菌（faecalis）・リステリアに要る。' },
      { abbr: 'AMPC', jp: 'アモキシシリン', memo: 'ABPCの経口版。ピロリ除菌にも使う。' },
      { abbr: 'PIPC', jp: 'ピペラシリン', memo: '抗緑膿菌ペニシリン。' },
      { abbr: 'MPIPC', jp: 'オキサシリン／メチシリン', memo: 'βラクタマーゼに壊されない。MRSA判定の基準薬。' },
    ],
  },
  {
    id: 'bli',
    name: 'βラクタマーゼ阻害薬 配合剤',
    en: 'β-lactam / β-lactamase inhibitor',
    big: 'βラクタム系',
    spectrum: 'グラム陽性・陰性・嫌気性菌まで広く。TAZ/PIPCは緑膿菌もカバー',
    note: 'βラクタマーゼを阻害する薬を足して、壊されるのを防ぐ。ESBLやAmpCには効かないことがある。',
    items: [
      { abbr: 'ABPC/SBT', jp: 'アンピシリン／スルバクタム', memo: 'スルバクタム自体がアシネトバクターに効く珍しい阻害薬。' },
      { abbr: 'AMPC/CVA', jp: 'アモキシシリン／クラブラン酸', memo: '経口。βラクタマーゼ産生のインフルエンザ菌・モラクセラに。BLNARには無効。' },
      { abbr: 'TAZ/PIPC', jp: 'タゾバクタム／ピペラシリン', memo: '広域。緑膿菌・嫌気性菌までカバー。' },
      { abbr: 'CTLZ/TAZ', jp: 'セフトロザン／タゾバクタム', memo: '耐性緑膿菌向けの新しい配合剤。' },
    ],
  },
  {
    id: 'ceph1',
    name: 'セファロスポリン系 第1世代',
    en: 'Cephalosporins (1st gen)',
    big: 'βラクタム系',
    spectrum: 'MSSA・溶連菌・大腸菌・肺炎桿菌・プロテウス（腸球菌とリステリアは効かない）',
    note: 'グラム陽性菌に強い。グラム陰性菌には弱い。腸球菌・リステリアには世代を問わず効かない。',
    items: [
      { abbr: 'CEZ', jp: 'セファゾリン', memo: 'MSSAの第一選択。周術期予防投与の定番。' },
      { abbr: 'CEX', jp: 'セファレキシン', memo: '経口。皮膚軟部組織感染。' },
    ],
  },
  {
    id: 'ceph2',
    name: 'セファロスポリン系 第2世代',
    en: 'Cephalosporins (2nd gen)',
    big: 'βラクタム系',
    spectrum: '第1世代＋インフルエンザ菌・モラクセラ。セファマイシン系は嫌気性菌も',
    note: '第1世代よりグラム陰性菌に少し強い。',
    items: [
      { abbr: 'CTM', jp: 'セフォチアム', memo: '' },
      { abbr: 'CXM', jp: 'セフロキシム', memo: '' },
    ],
  },
  {
    id: 'cephamycin',
    name: 'セファマイシン系',
    en: 'Cephamycins',
    big: 'βラクタム系',
    spectrum: 'グラム陰性桿菌＋嫌気性菌（Bacteroides）。ESBL産生菌にも残る',
    note: '構造上は第2世代の仲間だが、ESBLに壊されにくいのが最大の特徴。嫌気性菌にも効く。AmpC産生菌には壊される。',
    items: [
      { abbr: 'CMZ', jp: 'セフメタゾール', memo: 'ESBL産生菌の尿路感染で選択肢になる。ESBL確認試験の解釈にも使う。' },
      { abbr: 'FOX', jp: 'セフォキシチン', memo: '日本では治療薬というよりMRSAスクリーニング用のディスクとして出てくる。' },
    ],
  },
  {
    id: 'ceph3',
    name: 'セファロスポリン系 第3世代',
    en: 'Cephalosporins (3rd gen)',
    big: 'βラクタム系',
    spectrum: 'グラム陰性桿菌に広く。CTRX/CTXは緑膿菌に効かない、CAZは緑膿菌に効くがグラム陽性に弱い',
    note: 'グラム陰性菌に強い。ESBLに壊される。抗緑膿菌活性の有無で2つに分かれるのが要点。',
    items: [
      { abbr: 'CTX', jp: 'セフォタキシム', memo: '緑膿菌には効かない。' },
      { abbr: 'CTRX', jp: 'セフトリアキソン', memo: '緑膿菌には効かない。半減期が長く1日1回。髄膜炎・淋菌の主力。' },
      { abbr: 'CAZ', jp: 'セフタジジム', memo: '緑膿菌に効く。逆にグラム陽性菌には弱い。' },
    ],
  },
  {
    id: 'ceph4',
    name: 'セファロスポリン系 第4世代',
    en: 'Cephalosporins (4th gen)',
    big: 'βラクタム系',
    spectrum: 'グラム陽性＋陰性＋緑膿菌。AmpC産生菌にも安定',
    note: 'グラム陽性にも陰性にも効く。AmpCに壊されにくいのが第3世代との決定的な違い。',
    items: [
      { abbr: 'CFPM', jp: 'セフェピム', memo: 'AmpC産生菌（エンテロバクター等）で第3世代が耐性でも残ることが多い。緑膿菌にも効く。' },
    ],
  },
  {
    id: 'ceph5',
    name: 'セファロスポリン系 第5世代',
    en: 'Cephalosporins (5th gen)',
    big: 'βラクタム系',
    spectrum: 'MRSAを含むグラム陽性菌＋グラム陰性桿菌',
    note: 'MRSAに効くセファロスポリン。',
    items: [
      { abbr: 'CPT', jp: 'セフタロリン', memo: 'MRSAに活性あり。MRSAだからと一律にβラクタム耐性報告してはいけない例外。' },
    ],
  },
  {
    id: 'carbapenem',
    name: 'カルバペネム系',
    en: 'Carbapenems',
    big: 'βラクタム系',
    spectrum: 'グラム陽性・陰性・嫌気性菌をほぼ全部（腸球菌faecium・MRSA・ステノトロフォモナスは除く）',
    note: '最も広域。ESBLにもAmpCにも壊されない。切り札なので温存する。カルバペネマーゼ（KPC・IMP・NDM・OXA-48）にだけ壊される。',
    items: [
      { abbr: 'IPM/CS', jp: 'イミペネム／シラスタチン', memo: 'プロテウス・モルガネラ・プロビデンシアは生まれつきMICが高い。単独の非感性でCREと決めない。' },
      { abbr: 'MEPM', jp: 'メロペネム', memo: '髄膜炎に使える。痙攣リスクがイミペネムより低い。' },
      { abbr: 'DRPM', jp: 'ドリペネム', memo: '' },
      { abbr: 'BIPM', jp: 'ビアペネム', memo: '' },
      { abbr: 'ERTA', jp: 'エルタペネム', memo: '緑膿菌とアシネトバクターには効かない。ここが他のカルバペネムとの決定的な違い。' },
    ],
  },
  {
    id: 'monobactam',
    name: 'モノバクタム系',
    en: 'Monobactams',
    big: 'βラクタム系',
    spectrum: 'グラム陰性桿菌のみ（緑膿菌を含む）。グラム陽性菌・嫌気性菌には無効',
    note: 'グラム陰性菌にしか効かない。メタロβラクタマーゼ（MBL）には壊されない。',
    items: [
      { abbr: 'AZT', jp: 'アズトレオナム', memo: 'グラム陽性菌・嫌気性菌には無効。βラクタムアレルギーでも使えることがある。' },
    ],
  },
  {
    id: 'aminoglycoside',
    name: 'アミノグリコシド系',
    en: 'Aminoglycosides',
    big: '',
    spectrum: '好気性グラム陰性桿菌（緑膿菌を含む）。嫌気性菌には無効。単剤で腸球菌には無効',
    note: 'リボソーム30Sを阻害する。取り込みに酸素が要るので、嫌気性菌には生まれつき効かない。腎毒性・聴器毒性。',
    items: [
      { abbr: 'GM', jp: 'ゲンタマイシン', memo: '腸球菌の心内膜炎では高濃度スクリーニング（HLAR）で併用可否を見る。' },
      { abbr: 'TOB', jp: 'トブラマイシン', memo: '緑膿菌に強め。' },
      { abbr: 'AMK', jp: 'アミカシン', memo: '耐性酵素に壊されにくい。MDRP/MDRAの判定薬。' },
      { abbr: 'SM', jp: 'ストレプトマイシン', memo: '抗結核薬でもある。' },
      { abbr: 'ABK', jp: 'アルベカシン', memo: '日本独自。MRSAに使う。' },
    ],
  },
  {
    id: 'macrolide',
    name: 'マクロライド系',
    en: 'Macrolides',
    big: '',
    spectrum: 'グラム陽性球菌＋非定型（マイコプラズマ・レジオネラ・クラミジア）＋カンピロバクター・百日咳',
    note: 'リボソーム50Sを阻害する。細胞内移行がよく、非定型（マイコプラズマ・レジオネラ・クラミジア）に効く。',
    items: [
      { abbr: 'EM', jp: 'エリスロマイシン', memo: 'Dテスト（誘導型クリンダマイシン耐性）の相方。' },
      { abbr: 'CAM', jp: 'クラリスロマイシン', memo: 'ピロリ除菌・MAC治療の要。ここが耐性だと治療が組み直しになる。' },
      { abbr: 'AZM', jp: 'アジスロマイシン', memo: '半減期が非常に長い。カンピロバクター・淋菌・百日咳。' },
    ],
  },
  {
    id: 'lincomycin',
    name: 'リンコマイシン系',
    en: 'Lincosamides',
    big: '',
    spectrum: 'グラム陽性球菌＋嫌気性菌（横隔膜より上の嫌気性菌に強い）',
    note: 'マクロライドと同じ50Sに効くので、erm遺伝子による交差耐性（MLSb）が起きる。だからDテストが要る。',
    items: [
      { abbr: 'CLDM', jp: 'クリンダマイシン', memo: '毒素産生を抑える目的で使う（壊死性軟部組織感染・ガス壊疽）。嫌気性菌カバーだが Bacteroides の耐性が3〜4割。' },
    ],
  },
  {
    id: 'tetracycline',
    name: 'テトラサイクリン系',
    en: 'Tetracyclines',
    big: '',
    spectrum: 'グラム陽性・陰性・非定型・リケッチア。ステノトロフォモナス（MINO）',
    note: 'リボソーム30Sを阻害する。細胞内移行がよい。歯牙着色のため小児・妊婦は避ける。',
    items: [
      { abbr: 'MINO', jp: 'ミノサイクリン', memo: 'ステノトロフォモナス・アシネトバクターに使える。' },
      { abbr: 'DOXY', jp: 'ドキシサイクリン', memo: 'リケッチア・レプトスピラ・マイコプラズマ。' },
      { abbr: 'TGC', jp: 'チゲサイクリン', memo: 'グリシルサイクリン系。多剤耐性菌の最後の手段のひとつ。プロテウス・緑膿菌には効かない。' },
    ],
  },
  {
    id: 'quinolone',
    name: 'キノロン系（フルオロキノロン）',
    en: 'Fluoroquinolones',
    big: '',
    spectrum: 'グラム陰性桿菌に強い。LVFX/MFLXは肺炎球菌にも。MFLXは嫌気性菌にも（緑膿菌には無効）',
    note: 'DNAジャイレース／トポイソメラーゼを阻害する。QRDR変異で段階的に耐性化する。',
    items: [
      { abbr: 'CPFX', jp: 'シプロフロキサシン', memo: 'グラム陰性・緑膿菌に強い。肺炎球菌には弱い。' },
      { abbr: 'LVFX', jp: 'レボフロキサシン', memo: '呼吸器キノロン。肺炎球菌にも効く。MDRP/MDRAの判定薬。' },
      { abbr: 'MFLX', jp: 'モキシフロキサシン', memo: '嫌気性菌にも効く。緑膿菌には効かない。' },
      { abbr: 'NA', jp: 'ナリジクス酸', memo: '古いキノロン。今はサルモネラのFQ低感受性を見抜くスクリーニングとして使う。' },
    ],
  },
  {
    id: 'glycopeptide',
    name: 'グリコペプチド系',
    en: 'Glycopeptides',
    big: '',
    spectrum: 'グラム陽性菌のみ（MRSA・腸球菌・C. difficile）。グラム陰性菌には原理的に無効',
    note: '細胞壁合成を阻害する。分子が大きく、グラム陰性菌の外膜を通れないので陰性菌には効かない。',
    items: [
      { abbr: 'VCM', jp: 'バンコマイシン', memo: 'MRSA治療の基本。van遺伝子で耐性化（VRE）。Lactobacillus・Leuconostoc・C. innocuum は生まれつき耐性。' },
      { abbr: 'TEIC', jp: 'テイコプラニン', memo: 'vanA型VREは耐性、vanB型は感性のまま。型の判別に使える。' },
    ],
  },
  {
    id: 'oxazolidinone',
    name: 'オキサゾリジノン系',
    en: 'Oxazolidinones',
    big: '',
    spectrum: 'グラム陽性菌のみ（MRSA・VRE）',
    note: 'リボソーム50Sの開始複合体を阻害する。VRE・MRSAに効く。経口でも生体利用率が高い。',
    items: [
      { abbr: 'LZD', jp: 'リネゾリド', memo: 'VRE・MRSAの切り札。血小板減少に注意。' },
    ],
  },
  {
    id: 'lipopeptide',
    name: 'リポペプチド系',
    en: 'Lipopeptides',
    big: '',
    spectrum: 'グラム陽性菌のみ（MRSA・VRE）。肺炎には使えない',
    note: '細胞膜を脱分極させる。',
    items: [
      { abbr: 'DAP', jp: 'ダプトマイシン', memo: '肺サーファクタントで失活するので、肺炎には使えない。菌血症・心内膜炎・皮膚軟部組織に。' },
    ],
  },
  {
    id: 'polypeptide',
    name: 'ポリペプチド系',
    en: 'Polymyxins',
    big: '',
    spectrum: 'グラム陰性桿菌のみ（多剤耐性の緑膿菌・アシネトバクター・CRE）',
    note: '外膜のLPSに結合する。グラム陰性菌専用。多剤耐性菌の最後の手段。腎毒性が強い。',
    items: [
      { abbr: 'CL', jp: 'コリスチン（ポリミキシンE）', memo: 'プロテウス・セラチア・モルガネラ・プロビデンシア・バークホルデリアは生まれつき耐性。mcr遺伝子でプラスミド性の耐性が広がっている。' },
    ],
  },
  {
    id: 'stfolate',
    name: '葉酸合成阻害薬',
    en: 'Sulfonamides / Trimethoprim',
    big: '',
    spectrum: 'グラム陽性・陰性に広く。ステノトロフォモナス・ノカルジア・ニューモシスチス',
    note: '葉酸合成の2段階を同時に止める。腸球菌は培地では感性に見えるが生体内では無効。',
    items: [
      { abbr: 'ST', jp: 'スルファメトキサゾール／トリメトプリム（ST合剤）', memo: 'ステノトロフォモナス・ノカルジア・ニューモシスチスの第一選択。' },
    ],
  },
  {
    id: 'other-ab',
    name: 'その他の抗菌薬',
    en: 'Others',
    big: '',
    spectrum: '薬ごとに大きく違う。個別に確認する',
    note: '',
    items: [
      { abbr: 'MNZ', jp: 'メトロニダゾール', memo: '嫌気性菌・原虫。好気環境では活性化しない。Cutibacterium・Actinomyces・Bifidobacterium には効かない。' },
      { abbr: 'FOM', jp: 'ホスホマイシン', memo: '細胞壁合成の最初の段階を阻害。膀胱炎・腸管出血性大腸菌。' },
      { abbr: 'NIT', jp: 'ニトロフラントイン', memo: '尿路のみ。プロテウス・セラチアは生まれつき耐性。' },
      { abbr: 'CP', jp: 'クロラムフェニコール', memo: '再生不良性貧血のため国内ではほぼ使わない。' },
      { abbr: 'RFP', jp: 'リファンピシン', memo: 'RNAポリメラーゼ阻害。単剤では急速に耐性化するので必ず併用。バイオフィルム・人工物感染に。' },
    ],
  },
  {
    id: 'tb',
    name: '抗結核薬',
    en: 'Anti-tuberculosis',
    big: '',
    spectrum: '抗酸菌',
    note: 'INH と RFP の両方に耐性なら多剤耐性結核（MDR-TB）。',
    items: [
      { abbr: 'INH', jp: 'イソニアジド', memo: 'katG / inhA 変異で耐性化。' },
      { abbr: 'RFP', jp: 'リファンピシン', memo: 'rpoB 変異で耐性化。' },
      { abbr: 'EB', jp: 'エタンブトール', memo: '視神経障害。' },
      { abbr: 'PZA', jp: 'ピラジナミド', memo: '酸性環境でのみ効く。M. bovis・M. kansasii は生まれつき耐性。' },
      { abbr: 'SM', jp: 'ストレプトマイシン', memo: '' },
    ],
  },
  {
    id: 'azole',
    name: '抗真菌薬：アゾール系',
    en: 'Azoles',
    big: '抗真菌薬',
    spectrum: 'カンジダ（krusei除く）・アスペルギルス（VRCZ以降）・クリプトコッカス',
    note: 'エルゴステロール合成（CYP51）を阻害する。cyp51A変異で耐性化。',
    items: [
      { abbr: 'FLCZ', jp: 'フルコナゾール', memo: 'C. krusei は生まれつき耐性。C. glabrata は用量依存性感受性。アスペルギルスには効かない。' },
      { abbr: 'VRCZ', jp: 'ボリコナゾール', memo: 'アスペルギルスの第一選択。ムーコルには効かない（投与中にムーコルが出てくる）。' },
      { abbr: 'ITCZ', jp: 'イトラコナゾール', memo: '' },
      { abbr: 'PSCZ', jp: 'ポサコナゾール', memo: 'ムーコルにも効く数少ないアゾール。' },
    ],
  },
  {
    id: 'echinocandin',
    name: '抗真菌薬：エキノキャンディン系',
    en: 'Echinocandins',
    big: '抗真菌薬',
    spectrum: 'カンジダ・アスペルギルス。クリプトコッカスとムーコルには無効',
    note: '細胞壁のβ-1,3-グルカン合成を阻害する。FKS遺伝子変異で耐性化。',
    items: [
      { abbr: 'MCFG', jp: 'ミカファンギン', memo: 'カンジダ血症の第一選択。クリプトコッカスには生まれつき効かない（細胞壁の構造が違う）。' },
      { abbr: 'CPFG', jp: 'カスポファンギン', memo: 'C. parapsilosis はMICが生まれつき高い。' },
    ],
  },
  {
    id: 'polyene',
    name: '抗真菌薬：ポリエン系・その他',
    en: 'Polyenes / others',
    big: '抗真菌薬',
    spectrum: 'ほぼ全ての真菌（ムーコルを含む）',
    note: '',
    items: [
      { abbr: 'AMPH-B', jp: 'アムホテリシンB', memo: '最も広域。ムーコル・クリプトコッカスの要。腎毒性が強い（リポソーム製剤で軽減）。' },
      { abbr: '5-FC', jp: 'フルシトシン', memo: '単剤では急速に耐性化。クリプトコッカス髄膜炎でアムホテリシンBと併用。' },
    ],
  },
];
