/* 菌譜 — 耐性機序データベース
 *
 * 菌・抗菌薬・耐性機序の3つを相互リンクするハブ。
 * 「この菌でこの薬が耐性 → どの機序 → どう検出して、どう報告するか」を1本の線でつなぐ。
 *
 * organisms  … その機序が問題になる菌（rules.js の ORGANISMS の id）
 * classes    … その機序が壊す抗菌薬の系統（drugs.js の DRUG_CLASSES の id）
 * これも下書き。CLSI M100 最新版と自施設SOPで確認する。
 */

const MECHANISMS = [
  {
    id: 'esbl',
    abbr: 'ESBL',
    name: '基質特異性拡張型βラクタマーゼ',
    en: 'Extended-Spectrum β-Lactamase',
    type: '酵素による分解（Ambler class A）',
    summary: 'ペニシリナーゼが変異して、第3世代セファロスポリンとモノバクタムまで壊せるようになったもの。プラスミド性なので菌から菌へ伝わる。',
    genes: 'CTX-M型（世界で最多。日本でもこれ）／ TEM型 ／ SHV型',
    breaks: '第3世代・第4世代セファロスポリン、ペニシリン系、アズトレオナム',
    spared: 'セファマイシン系（セフメタゾール）、カルバペネム系、βラクタマーゼ阻害薬配合剤（クラブラン酸で阻害される）',
    detect: [
      'クラブラン酸併用のESBL確認試験。CAZ単独 vs CAZ/CVA、CTX単独 vs CTX/CVA を比較し、阻害薬を足して阻止円が一定以上広がれば陽性',
      'クラブラン酸で阻害される、が定義そのもの。ここがAmpCとの決定的な分かれ目',
    ],
    pitfall: 'AmpCを併せ持つ株ではクラブラン酸の効きが隠れ、ESBL確認試験が偽陰性になる。セファマイシンも耐性ならAmpCを疑う。',
    organisms: ['ecoli', 'kpneumoniae', 'koxytoca', 'pmirabilis', 'salmonella', 'shigella'],
    classes: ['ceph3', 'ceph4', 'penicillin', 'monobactam'],
    rule: 'esbl',
  },
  {
    id: 'ampc',
    abbr: 'AmpC',
    name: 'AmpC型βラクタマーゼ（セファロスポリナーゼ）',
    en: 'AmpC β-lactamase',
    type: '酵素による分解（Ambler class C）',
    summary: '多くのグラム陰性桿菌が染色体に持っている。普段は眠っているが、βラクタムに曝されると誘導されて大量に作られる。だから「初回は感性、治療中に耐性化」が起きる。',
    genes: '染色体性（誘導型）／ プラスミド性（CMY型・DHA型 など、恒常的に発現）',
    breaks: '第1〜第3世代セファロスポリン、セファマイシン系、ペニシリン系、βラクタマーゼ阻害薬配合剤',
    spared: 'セフェピム（第4世代）、カルバペネム系',
    detect: [
      'セファマイシン（セフメタゾール）まで耐性なら AmpC を疑う。ESBLならセファマイシンは感性で残る',
      'ボロン酸による阻害試験で確認できる（クラブラン酸では阻害されない）',
    ],
    pitfall: '誘導型AmpCを持つ菌群（エンテロバクター・シトロバクターフロインディ・セラチア・モルガネラ・プロビデンシア・K. aerogenes）では、第3世代セファロスポリンが「感性」と出ても治療中に耐性化する。感性をそのまま報告するのが最も危険。',
    organisms: ['enterobacter', 'cfreundii', 'kaerogenes', 'smarcescens', 'morganella', 'providencia'],
    classes: ['ceph1', 'ceph2', 'ceph3', 'cephamycin', 'penicillin', 'bli'],
    rule: 'ampc',
  },
  {
    id: 'kpc',
    abbr: 'KPC',
    name: 'KPC型カルバペネマーゼ',
    en: 'Klebsiella pneumoniae carbapenemase',
    type: '酵素による分解（Ambler class A・セリン型）',
    summary: 'カルバペネムまで壊すセリン型酵素。米国・南欧・中国で主流。日本では少ない。',
    genes: 'blaKPC（プラスミド性）',
    breaks: 'カルバペネム系を含む、ほぼ全てのβラクタム（アズトレオナムも）',
    spared: 'セリン型なので、アビバクタム等の新しい阻害薬で阻害できる。EDTAでは阻害されない（ここがMBLとの違い）',
    detect: [
      'mCIM 陽性 かつ eCIM 陰性 → セリン型カルバペネマーゼ（KPC・OXA-48）を示唆',
      'ボロン酸阻害試験で阻害される',
      '確定は遺伝子検査（blaKPC）',
    ],
    pitfall: 'MBL（IMP/NDM/VIM）と違い金属イオンを要求しないので、EDTA/SMA阻害試験は陰性になる。「SMA陰性＝カルバペネマーゼではない」と早合点しない。',
    organisms: ['kpneumoniae', 'ecoli', 'enterobacter'],
    classes: ['carbapenem', 'ceph3', 'ceph4', 'penicillin', 'monobactam'],
    rule: 'cre',
  },
  {
    id: 'imp',
    abbr: 'IMP',
    name: 'IMP型メタロβラクタマーゼ（MBL）',
    en: 'Imipenemase',
    type: '酵素による分解（Ambler class B・金属型）',
    summary: '活性中心に亜鉛を持つ金属酵素。日本のカルバペネマーゼで最も多いのがこのIMP型。緑膿菌でも腸内細菌目でも出る。',
    genes: 'blaIMP（プラスミド性・インテグロン上に載って広がる）',
    breaks: 'カルバペネム系を含むほぼ全てのβラクタム',
    spared: 'アズトレオナム（モノバクタム）は MBL に壊されない。ただし多くの株は別のESBL/AmpCも併せ持つので、結局アズトレオナムも効かないことが多い',
    detect: [
      'SMA（メルカプト酢酸ナトリウム）阻害試験。金属をキレートすると活性が消えるので阻止円が広がる',
      'mCIM 陽性 かつ eCIM 陽性 → MBL（eCIMはEDTAで金属を奪う原理）',
      '確定は遺伝子検査（blaIMP）',
    ],
    pitfall: 'IMP型は基質分解が弱く、カルバペネムのMICが感性域にとどまることがある。「MIC感性だからカルバペネマーゼ非産生」とは言えない。日本で見逃されやすい理由がここ。',
    organisms: ['paeruginosa', 'kpneumoniae', 'ecoli', 'enterobacter', 'abaumannii'],
    classes: ['carbapenem', 'ceph3', 'ceph4', 'penicillin'],
    rule: 'cre',
  },
  {
    id: 'ndm',
    abbr: 'NDM',
    name: 'NDM型メタロβラクタマーゼ（MBL）',
    en: 'New Delhi metallo-β-lactamase',
    type: '酵素による分解（Ambler class B・金属型）',
    summary: 'インド亜大陸を中心に世界へ広がったMBL。分解力が強く、カルバペネムのMICが明確に上がる。海外渡航歴・海外医療機関受診歴が手がかりになる。',
    genes: 'blaNDM（プラスミド性）',
    breaks: 'カルバペネム系を含むほぼ全てのβラクタム',
    spared: 'アズトレオナム（理論上）／ セフィデロコル',
    detect: [
      'SMA・EDTA阻害試験 陽性',
      'mCIM 陽性 かつ eCIM 陽性',
      '確定は遺伝子検査（blaNDM）',
    ],
    pitfall: '海外渡航歴のある患者の腸内細菌目でカルバペネム耐性を見たら必ず疑う。院内伝播すると制御が難しい。',
    organisms: ['kpneumoniae', 'ecoli', 'enterobacter', 'abaumannii'],
    classes: ['carbapenem', 'ceph3', 'ceph4', 'penicillin'],
    rule: 'cre',
  },
  {
    id: 'oxa',
    abbr: 'OXA',
    name: 'OXA型βラクタマーゼ（オキサシリナーゼ）',
    en: 'Oxacillinase',
    type: '酵素による分解（Ambler class D・セリン型）',
    summary: '種類が非常に多い。OXA-48型は腸内細菌目のカルバペネマーゼ、OXA-23/40/58型はアシネトバクターのカルバペネム耐性の主役。',
    genes: 'blaOXA-48（腸内細菌目）／ blaOXA-23・-24/40・-58（アシネトバクター）',
    breaks: 'OXA-48：カルバペネム（弱く分解）。OXA-23等：カルバペネム',
    spared: 'OXA-48は第3世代セファロスポリンを壊さない（そこは温存される）ため、耐性像が中途半端に見える',
    detect: [
      'mCIM 陽性 かつ eCIM 陰性 → セリン型（OXA-48・KPC）',
      'ボロン酸・EDTAのどちらでも阻害されにくい。表現型検査で最も見抜きにくい',
      '確定は遺伝子検査',
    ],
    pitfall: 'OXA-48はカルバペネムのMIC上昇がわずかで、感性域に見えることがある。表現型だけでは検出できない代表格。エルタペネムの非感性が唯一の手がかりになることがある。',
    organisms: ['kpneumoniae', 'ecoli', 'abaumannii'],
    classes: ['carbapenem', 'penicillin'],
    rule: 'cre',
  },
  {
    id: 'mrsa',
    abbr: 'MRSA',
    name: 'メチシリン耐性黄色ブドウ球菌（PBP2\'の獲得）',
    en: 'Methicillin-resistant S. aureus',
    type: '作用点の変化（PBPの置換）',
    summary: '酵素で薬を壊すのではなく、βラクタムが結合できない別のペニシリン結合タンパク（PBP2\' / PBP2a）を新しく作る。だから阻害薬を足しても無駄。',
    genes: 'mecA（SCCmec上）／ mecC（稀）',
    breaks: 'ほぼ全てのβラクタム（ペニシリン・セファロスポリン・カルバペネム・阻害薬配合剤）',
    spared: 'セフタロリン（第5世代セファロスポリン）はPBP2\'に結合できる。バンコマイシン・リネゾリド・ダプトマイシン',
    detect: [
      'セフォキシチン（FOX）ディスクによるスクリーニング。オキサシリンより検出感度が高い',
      'PBP2\' 検出（ラテックス凝集法）',
      '確定は mecA / mecC 遺伝子検査',
    ],
    pitfall: 'メチシリン耐性なら、in vitro でセファロスポリンやカルバペネムが「感性」と出ても、すべて耐性として報告する。ただしセフタロリンだけは例外。',
    organisms: ['saureus', 'cns', 'slugdunensis'],
    classes: ['penicillin', 'ceph1', 'ceph2', 'ceph3', 'ceph4', 'carbapenem', 'bli'],
    rule: 'mrsa',
  },
  {
    id: 'vre',
    abbr: 'VRE',
    name: 'バンコマイシン耐性腸球菌（van遺伝子）',
    en: 'Vancomycin-resistant Enterococcus',
    type: '作用点の変化（細胞壁前駆体の末端置換）',
    summary: 'バンコマイシンが結合する D-Ala-D-Ala の末端を D-Ala-D-Lac（または D-Ser）に作り替える。結合できなくなるので効かない。',
    genes: 'vanA（VCM耐性・TEIC耐性）／ vanB（VCM耐性・TEIC感性）／ vanC（gallinarum・casseliflavus の自然耐性、低度）',
    breaks: 'バンコマイシン（vanAはテイコプラニンも）',
    spared: 'リネゾリド、ダプトマイシン、チゲサイクリン',
    detect: [
      'バンコマイシンのMIC測定（ディスク法だけで済ませない）',
      'テイコプラニンを併せて測ると vanA / vanB の見当がつく',
      '確定は van遺伝子検査。菌種同定も必ず確定させる',
    ],
    pitfall: 'E. gallinarum / casseliflavus は vanC による自然耐性であってVREではない。ここを取り違えると、不要な隔離とアウトブレイク対応が走る。',
    organisms: ['efaecium', 'efaecalis', 'evanc'],
    classes: ['glycopeptide'],
    rule: 'vre',
  },
  {
    id: 'cre',
    abbr: 'CRE',
    name: 'カルバペネム耐性腸内細菌目細菌',
    en: 'Carbapenem-resistant Enterobacterales',
    type: '表現型のまとまり（機序はひとつではない）',
    summary: '機序の名前ではなく「カルバペネムが効かない腸内細菌目」という結果の呼び名。中身は①カルバペネマーゼ産生（CPE）②ESBL/AmpC＋外膜ポーリン欠損、の2通りある。',
    genes: 'CPEなら blaIMP / blaNDM / blaKPC / blaOXA-48 など。非CPEなら ompK35/36 等のポーリン欠損＋ESBL/AmpC',
    breaks: 'カルバペネム系',
    spared: '株による。コリスチン・チゲサイクリン・アミカシン・新規βラクタマーゼ阻害薬配合剤が残ることがある',
    detect: [
      'mCIM でカルバペネマーゼ産生の有無を判定する',
      'eCIM を併用して MBL かどうかを分ける（eCIM陽性＝MBL）',
      'mCIM陰性でも耐性は耐性。ポーリン欠損型のCREは伝播力が低いが、治療は同じく難しい',
    ],
    pitfall: 'イミペネムだけが非感性の Proteus / Providencia / Morganella は、生まれつきMICが高いだけのことがある。CREと決める前に他のカルバペネムも測る。',
    organisms: ['ecoli', 'kpneumoniae', 'koxytoca', 'kaerogenes', 'enterobacter', 'cfreundii', 'smarcescens', 'pmirabilis', 'morganella', 'providencia'],
    classes: ['carbapenem'],
    rule: 'cre',
    notify: '感染症法5類全数届出',
  },
  {
    id: 'mdrp',
    abbr: 'MDRP',
    name: '多剤耐性緑膿菌',
    en: 'Multidrug-resistant P. aeruginosa',
    type: '表現型のまとまり（複数機序の重なり）',
    summary: 'カルバペネム・アミノグリコシド・フルオロキノロンの3系統すべてに耐性。機序はMBL産生・外膜ポーリン(OprD)欠損・薬剤排出ポンプ亢進・作用点変異の重なり。',
    genes: 'blaIMP / blaVIM（MBL）／ oprD欠損 ／ mexAB-oprM 等の排出ポンプ亢進',
    breaks: 'カルバペネム、アミノグリコシド、フルオロキノロン',
    spared: 'コリスチンが残ることが多い。株によってはセフトロザン/タゾバクタム',
    detect: [
      '3系統すべてで耐性を再確認する（判定基準は届出基準・施設SOPで確認）',
      'MBL産生を SMA阻害試験 または mCIM/eCIM で確認する',
      'イミペネムだけ耐性でメロペネム感性なら、MBLではなくOprD欠損の可能性が高い',
    ],
    pitfall: '緑膿菌はエルタペネムに生まれつき耐性。これをカルバペネム耐性と数えない。',
    organisms: ['paeruginosa'],
    classes: ['carbapenem', 'aminoglycoside', 'quinolone'],
    rule: 'mdrp',
    notify: '感染症法5類全数届出',
  },
  {
    id: 'crab',
    abbr: 'CRAB / MDRA',
    name: 'カルバペネム耐性・多剤耐性アシネトバクター',
    en: 'Carbapenem-resistant / Multidrug-resistant A. baumannii',
    type: '表現型のまとまり（OXA型カルバペネマーゼが主役）',
    summary: 'アシネトバクターのカルバペネム耐性は、OXA-23/24/58型カルバペネマーゼが主役。MDRAはさらにアミノグリコシド・フルオロキノロンも耐性。',
    genes: 'blaOXA-23 / -24(40) / -58 ／ blaIMP・blaNDM（MBL）も',
    breaks: 'カルバペネム、アミノグリコシド、フルオロキノロン',
    spared: 'コリスチン、ミノサイクリン、スルバクタム（スルバクタム自体に抗菌活性がある）',
    detect: [
      '3系統すべてで耐性を再確認する',
      'カルバペネマーゼ（OXA型）の確認を検討する',
    ],
    pitfall: '乾燥した環境表面で数週間生きる。1株出たら周囲環境と他患者のスクリーニングを考える。アシネトバクターはエルタペネムとアズトレオナムに生まれつき耐性。',
    organisms: ['abaumannii'],
    classes: ['carbapenem', 'aminoglycoside', 'quinolone'],
    rule: 'mdra',
    notify: '感染症法5類全数届出（MDRA）',
  },
  {
    id: 'mlsb',
    abbr: 'MLSb',
    name: '誘導型クリンダマイシン耐性（erm遺伝子）',
    en: 'inducible MLSb resistance',
    type: '作用点の変化（リボソーム50Sのメチル化）',
    summary: 'ermがリボソーム50Sをメチル化し、マクロライド・リンコマイシン・ストレプトグラミンBがまとめて効かなくなる。普段は眠っていて、マクロライドに曝されると誘導される。',
    genes: 'erm(A) / erm(B) / erm(C)',
    breaks: 'マクロライド系、クリンダマイシン（誘導後）',
    spared: 'msrA型（排出ポンプ）ならクリンダマイシンは効いたまま。Dテスト陰性がこれ',
    detect: [
      'Dテスト（ディスク近接法）。エリスロマイシン耐性かつクリンダマイシン感性のときだけ実施する',
      'クリンダマイシン側の阻止円がエリスロマイシン側へ向かって平坦化（D字型）すれば陽性',
    ],
    pitfall: 'エリスロマイシン耐性＋クリンダマイシン感性、という組み合わせに気づかないと、Dテスト自体が実施されない。感性のまま報告すると治療中に耐性化する。',
    organisms: ['saureus', 'cns', 'spyogenes', 'sagalactiae', 'spneumoniae'],
    classes: ['macrolide', 'lincomycin'],
    rule: 'dtest',
  },
  {
    id: 'blnar',
    abbr: 'BLNAR',
    name: 'βラクタマーゼ非産生アンピシリン耐性（PBP変異）',
    en: 'β-lactamase-negative ampicillin-resistant',
    type: '作用点の変化（PBP3の変異）',
    summary: 'インフルエンザ菌のアンピシリン耐性には2通りある。βラクタマーゼを作るタイプ（BLPAR）と、PBPが変異して薬が結合できないタイプ（BLNAR）。使える薬が真逆になる。',
    genes: 'ftsI（PBP3）変異',
    breaks: 'アンピシリン、クラブラン酸配合剤（阻害薬を足しても無駄）',
    spared: '第3世代セファロスポリン、カルバペネム、フルオロキノロン',
    detect: [
      'ニトロセフィン法でβラクタマーゼ産生を確認する',
      'βラクタマーゼ陰性なのにアンピシリン耐性 → BLNAR',
    ],
    pitfall: 'BLNARにクラブラン酸配合剤を「感性」と報告してはいけない。阻害薬は無意味。',
    organisms: ['hinfluenzae'],
    classes: ['penicillin', 'bli'],
    rule: 'blnar',
  },
  {
    id: 'visa',
    abbr: 'VISA / hVISA / VRSA',
    name: 'バンコマイシン低感受性・耐性黄色ブドウ球菌',
    en: 'Vancomycin-intermediate / resistant S. aureus',
    type: 'VISA＝細胞壁の肥厚／VRSA＝vanA獲得',
    summary: 'VISAは細胞壁が厚くなってバンコマイシンが標的まで届かなくなる（段階的）。VRSAは腸球菌からvanAを丸ごともらったもので、極めて稀。',
    genes: 'VISA：細胞壁合成関連の多段階変異 ／ VRSA：vanA',
    breaks: 'バンコマイシン（VRSAはテイコプラニンも）',
    spared: 'リネゾリド、ダプトマイシン（ただしVISAではDAPのMICも上がりやすい）',
    detect: [
      'ディスク法では検出できない。必ずMIC法で測る',
      'hVISAは通常のMIC測定では感性に見える。population analysis が要り、一般検査室では困難',
    ],
    pitfall: 'バンコマイシンのMICが上がってきているのに「感性」と報告し続けると、治療失敗の理由が見えなくなる。MICの推移そのものを臨床へ伝える。',
    organisms: ['saureus'],
    classes: ['glycopeptide'],
    rule: 'vrsa',
    notify: 'VRSAは感染症法5類全数届出',
  },
];
